name: Build release

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install libxcb-shape0-dev libxcb-xkb-dev -y
      - name: Cargo build
        run: |
          cargo build --verbose
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install libxcb-shape0-dev libxcb-xkb-dev -y
      - name: Cargo test
        run: |
          cargo test --verbose
